Repository torstenheavner/Codes, pull requests merged in 2020-02, with the labels that each got.

#1 poopyhead
  2MS2A/dnd.py
Labels: wontfix

#2 fuck you
  2MS2A/wink.py
Labels: bug

#4 me
  2MS2A/nat.py
Labels: enhancement

#6 vbeh
  2MS2A/nat.py
Labels: invalid
